#!/bin/sh
set -eu

cd /app

if [ "$1" = "start" ]; then
    echo "Running alembic migrations"
    alembic upgrade head
    echo "Starting API server"
    exec uvicorn src.api.app:app --host 0.0.0.0 --port 8000
else
    echo "Executing command: $@"
    exec python -m src.cli $@
fi
