#!/bin/sh
set -eu -o pipefail

cd /app

if [ "$1" == "start" ]; then
    echo "Starting API server"
    exec uvicorn src.api.nextcloud_news.app:app --host 0.0.0.0 --port 8000
elif [ "$1" == "update" ]; then
    echo "Updating feeds"
    exec python src/cli.py update
else
    echo "Unknown command: $1"
    exit 1
fi
