name: Cleanup Docker Images

on:
  schedule:
    # Run weekly on Sundays at 02:00 UTC
    - cron: '0 2 * * 0'
  workflow_dispatch: # Allow manual trigger

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Delete untagged container images older than 30 days
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          package: headless-rss
          delete-untagged: true
          older-than: 30 days
          token: ${{ secrets.GITHUB_TOKEN }}